// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  messages: [],
  input: "",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function Message(fields) {
  return { text: fields.text ?? null, isMine: fields.isMine ?? true };
}

function sendMessage() {
  state.messages = state.messages;
  state.input = "";
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="">
            <h1 class="aura-heading text-bold" style="padding: 8px; font-size: 1.25rem">Chat</h1>
            <div class="aura-scroll">
                <div class="aura-column" style="gap: 4px">
${state.messages.map((msg, _idx) => `<div class="aura-row" style="">
                            <span class="aura-text rounded" style="padding: 8px; border-radius: 8px">${msg.text}</span>
                        </div>`).join('')}                </div>
            </div>
            <div class="aura-row bg-surface" style="gap: 4px; padding: 8px">
                <input class="aura-input" type="text" placeholder="Type a message..." data-bind="input" value="${state.input || ''}"/>
                <button class="aura-button icon color-accent" onclick="sendMessage()">${_icon('arrow.up')}</button>
            </div>
        </div>
`;
}

const _icons = {'arrow.up':'⬆️','arrow.up.circle.fill':'⬆️','trash':'🗑','trash.fill':'🗑','plus':'+','plus.circle':'+','minus':'−','star':'⭐','star.fill':'⭐','heart':'❤️','heart.fill':'❤️','checkmark':'✅','checkmark.circle':'✅','xmark':'❌','magnifyingglass':'🔍','gear':'⚙️','person':'👤','house':'🏠','bell':'🔔','camera':'📷','photo':'🖼️','sun.max':'☀️','cloud':'☁️','cloud.rain':'🌧️','cloud.snow':'🌨️','drop':'💧','wind':'💨','lock.circle':'🔒','lock':'🔒','phone':'📞','video':'📹','mic':'🎤','cart':'🛒','inbox':'📥','square.and.pencil':'✏️','bubble.left.and.bubble.right':'💬',};
function _icon(n) { return _icons[n] || n; }

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
