// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  messages: list({  }),
  input: "",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function Message(fields) {
  return { text: fields.text ?? null, isMine: fields.isMine ?? true };
}

function sendMessage() {
  state.messages = state.messages;
  state.input = "";
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="">
            <h1 class="aura-heading" style="padding: 8px">Chat</h1>
            <div class="aura-scroll">
                <div class="aura-column" style="gap: 4px">
${state.messages.map(msg => `<div class="aura-row" style="">
                            <span class="aura-text">${state.msg.text}</span>
                        </div>`).join('')}                </div>
            </div>
            <div class="aura-row" style="gap: 4px">
                <input class="aura-input" type="text" placeholder="Type a message..." data-bind="input" value="${state.input || ''}"/>
                <button class="aura-button icon color-accent" onclick="sendMessage()">arrow.up</button>
            </div>
        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
