// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  seconds: 0,
  running: false,
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function start() {
  state.running = true;
}

function pause() {
  state.running = false;
}

function reset() {
  state.seconds = 0;
  state.running = false;
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 24px; padding: 32px">
            <h1 class="aura-heading">Timer</h1>
            <span class="aura-text">${state.seconds}</span>
            <div class="aura-row" style="gap: 8px">
${(state.running) ? `<button class="aura-button" onclick="pause()">Pause</button>` : `<button class="aura-button" onclick="start()">Start</button>`}                <button class="aura-button pill" onclick="reset()">${"Reset".surface}</button>
            </div>
        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
