// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  tasks: [],
  input: "",
  filter: "all",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function Task(fields) {
  return { title: fields.title ?? null, done: fields.done ?? false, priority: fields.priority ?? "low" };
}

function addTask(title) {
  state.tasks = [...state.tasks, Task({ title: title })];
  state.input = "";
}

function deleteTask(task) {
  state.tasks = state.tasks.filter(_item => _item !== task);
}

function showAll() {
  state.filter = "all";
}

function showActive() {
  state.filter = "active";
}

function showDone() {
  state.filter = "done";
}

function taskCount() {
  return "tasks";
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 16px; padding: 16px">
            <div class="aura-column text-center" style="gap: 2px; padding: 16px; text-align: center; align-items: center">
                <h1 class="aura-heading text-bold" style="font-size: 1.5rem">TaskFlow</h1>
                <span class="aura-text">Stay organized, stay productive</span>
            </div>
            <div class="aura-row" style="gap: 4px">
                <input class="aura-input" type="text" placeholder="What needs to be done?" data-bind="input" value="${state.input || ''}"/>
                <button class="aura-button" onclick="addTask(state.input)">Add</button>
            </div>
            <div class="aura-row" style="gap: 4px">
                <button class="aura-button pill" onclick="showAll()">All</button>
                <button class="aura-button pill" onclick="showActive()">Active</button>
                <button class="aura-button pill" onclick="showDone()">Done</button>
            </div>
            <div class="aura-column" style="gap: 4px">
                <span class="aura-text text-center" style="text-align: center; align-items: center">taskCount</span>
            </div>
            <div class="aura-column" style="gap: 2px">
${state.tasks.map((task, _idx) => `<div class="aura-row text-center" style="gap: 8px; padding: 8px; text-align: center; align-items: center">
                        <input class="aura-checkbox" type="checkbox" data-bind="task.done" ${(task.done) ? 'checked' : ''}/>
                        <div class="aura-column" style="gap: 2px">
                            <span class="aura-text">${task.title}</span>
                        </div>
                        <div class="aura-spacer"></div>
                        <button class="aura-button icon color-danger" onclick="deleteTask(' + JSON.stringify(task) + ')">${_icon('trash')}</button>
                    </div>`).join('')}            </div>
${((state.tasks.length === 0)) ? `<div class="aura-column text-center" style="gap: 8px; padding: 32px; text-align: center; align-items: center">
                <span class="aura-icon color-muted">${_icon('inbox')}</span>
                <span class="aura-text color-muted">No tasks yet</span>
                <span class="aura-text">Add your first task above</span>
            </div>` : ``}        </div>
`;
}

const _icons = {'arrow.up':'⬆️','arrow.up.circle.fill':'⬆️','trash':'🗑','trash.fill':'🗑','plus':'+','plus.circle':'+','minus':'−','star':'⭐','star.fill':'⭐','heart':'❤️','heart.fill':'❤️','checkmark':'✅','checkmark.circle':'✅','xmark':'❌','magnifyingglass':'🔍','gear':'⚙️','person':'👤','house':'🏠','bell':'🔔','camera':'📷','photo':'🖼️','sun.max':'☀️','cloud':'☁️','cloud.rain':'🌧️','cloud.snow':'🌨️','drop':'💧','wind':'💨','lock.circle':'🔒','lock':'🔒','phone':'📞','video':'📹','mic':'🎤','cart':'🛒','inbox':'📥','square.and.pencil':'✏️','bubble.left.and.bubble.right':'💬',};
function _icon(n) { return _icons[n] || n; }

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
