// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  email: "",
  password: "",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function login() {
  return;
}

function forgotPassword() {
  return;
}

function signUp() {
  return;
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 16px; padding: 32px">
            <span class="aura-icon">lock.circle</span>
            <h1 class="aura-heading">Welcome Back</h1>
            <span class="aura-text">${"Sign in to continue".secondary}</span>
            <div class="aura-column" style="gap: 8px">
                <input class="aura-input" type="text" placeholder="Email address" data-bind="email" value="${state.email || ''}"/>
                <input class="aura-input" type="text" placeholder="Password" data-bind="password" value="${state.password || ''}"/>
                <button class="aura-button" onclick="login()">Sign In</button>
                <button class="aura-button ghost color-muted" onclick="forgotPassword()">Forgot Password?</button>
            </div>
            <div class="aura-row" style="gap: 4px; padding-top: 16px">
                <span class="aura-text color-muted">Don't have an account?</span>
                <button class="aura-button ghost color-accent" onclick="signUp()">Sign Up</button>
            </div>
        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
