// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  photos: list({  }),
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function addPhoto() {
  state.photos = state.photos;
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 8px; padding: 8px">
            <div class="aura-row" style="">
                <h1 class="aura-heading">Gallery</h1>
                <div class="aura-spacer"></div>
                <button class="aura-button icon color-accent" onclick="addPhoto()">camera</button>
            </div>
            <div class="aura-grid">
${state.photos.map(photo => `<!-- unsupported -->`).join('')}            </div>
${(state.photos.isEmpty) ? `<div class="aura-column" style="gap: 8px; padding: 32px">
                <span class="aura-icon">photo</span>
                <span class="aura-text color-muted">No photos yet</span>
                <button class="aura-button" onclick="addPhoto()">Take Photo</button>
            </div>` : ``}        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
