// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  photos: [],
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function addPhoto() {
  state.photos = state.photos;
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 8px; padding: 8px">
            <div class="aura-row text-center" style="text-align: center; align-items: center">
                <h1 class="aura-heading text-bold" style="font-size: 1.25rem">Gallery</h1>
                <div class="aura-spacer"></div>
                <button class="aura-button icon color-accent" onclick="addPhoto()">${_icon('camera')}</button>
            </div>
            <div class="aura-grid">
${state.photos.map((photo, _idx) => `<!-- unsupported -->`).join('')}            </div>
${((state.photos.length === 0)) ? `<div class="aura-column text-center" style="gap: 8px; padding: 32px; text-align: center; align-items: center">
                <span class="aura-icon color-muted">${_icon('photo')}</span>
                <span class="aura-text color-muted">No photos yet</span>
                <button class="aura-button" onclick="addPhoto()">Take Photo</button>
            </div>` : ``}        </div>
`;
}

const _icons = {'arrow.up':'⬆️','arrow.up.circle.fill':'⬆️','trash':'🗑','trash.fill':'🗑','plus':'+','plus.circle':'+','minus':'−','star':'⭐','star.fill':'⭐','heart':'❤️','heart.fill':'❤️','checkmark':'✅','checkmark.circle':'✅','xmark':'❌','magnifyingglass':'🔍','gear':'⚙️','person':'👤','house':'🏠','bell':'🔔','camera':'📷','photo':'🖼️','sun.max':'☀️','cloud':'☁️','cloud.rain':'🌧️','cloud.snow':'🌨️','drop':'💧','wind':'💨','lock.circle':'🔒','lock':'🔒','phone':'📞','video':'📹','mic':'🎤','cart':'🛒','inbox':'📥','square.and.pencil':'✏️','bubble.left.and.bubble.right':'💬',};
function _icon(n) { return _icons[n] || n; }

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
