// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  temperature: 72,
  condition: "Sunny",
  city: "San Francisco",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 24px; padding: 32px">
            <span class="aura-text">${state.city}</span>
            <span class="aura-icon">sun.max</span>
            <span class="aura-text">${state.temperature}</span>
            <span class="aura-text">${state.condition.secondary}</span>
            <hr class="aura-divider"/>
            <h1 class="aura-heading" style="padding-top: 16px">Forecast</h1>
            <div class="aura-row" style="gap: 16px">
                <div class="aura-column" style="gap: 2px">
                    <span class="aura-text color-muted">Mon</span>
                    <span class="aura-icon">${"cloud".secondary}</span>
                    <span class="aura-text">68</span>
                </div>
                <div class="aura-column" style="gap: 2px">
                    <span class="aura-text color-muted">Tue</span>
                    <span class="aura-icon color-info">cloud.rain</span>
                    <span class="aura-text">62</span>
                </div>
                <div class="aura-column" style="gap: 2px">
                    <span class="aura-text color-muted">Wed</span>
                    <span class="aura-icon color-warning">sun.max</span>
                    <span class="aura-text">75</span>
                </div>
            </div>
        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
