// Aura App — Generated by Aura Compiler
'use strict';

const _state = {
  darkMode: false,
  notifications: true,
  volume: 75,
  language: "English",
};

const state = new Proxy(_state, {
  set(target, prop, value) {
    target[prop] = value;
    _scheduleRender();
    return true;
  }
});

let _renderPending = false;
function _scheduleRender() {
  if (!_renderPending) {
    _renderPending = true;
    requestAnimationFrame(() => { _renderPending = false; render(); });
  }
}

function signOut() {
  return;
}

function render() {
  const app = document.getElementById('app');
  if (!app) return;
  app.innerHTML = renderView();
  _bindEvents();
}

function renderView() {
  return `
        <div class="aura-column" style="gap: 8px; padding: 16px">
            <h1 class="aura-heading">Settings</h1>
            <div class="aura-column" style="gap: 4px; padding: 8px">
                <label class="aura-toggle"><input type="checkbox" data-bind="darkMode"/> Dark Mode</label>
                <hr class="aura-divider"/>
                <label class="aura-toggle"><input type="checkbox" data-bind="notifications"/> Notifications</label>
                <hr class="aura-divider"/>
                <div class="aura-row" style="gap: 8px">
                    <span class="aura-text">${"Volume".medium}</span>
                    <!-- unsupported -->
                </div>
            </div>
            <div class="aura-column" style="gap: 4px; padding: 8px">
                <div class="aura-row" style="">
                    <span class="aura-text">${"Language".medium}</span>
                    <div class="aura-spacer"></div>
                    <span class="aura-text">${state.language.secondary}</span>
                </div>
            </div>
            <button class="aura-button" onclick="signOut()">Sign Out</button>
        </div>
`;
}

function _bindEvents() {
  // Bind input elements to state
  document.querySelectorAll('[data-bind]').forEach(el => {
    const key = el.dataset.bind;
    if (el.type === 'checkbox') {
      el.checked = !!state[key];
      el.onchange = () => { state[key] = el.checked; };
    } else {
      el.value = state[key] || '';
      el.oninput = () => { state[key] = el.value; };
    }
  });
}

// Initialize on DOM ready
document.addEventListener('DOMContentLoaded', render);
